---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: rosa-cloudwatch-metrics-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
              name: iam-external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: amazon-cloudwatch
  name: rosa-cloudwatch-metrics-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: rosa-cloudwatch-metrics-secret-store
    kind: SecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rosa-cloudwatch-metrics-credentials
      decodingStrategy: Base64
