---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: rosa-rds-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
              name: iam-external-secrets-rds-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: openshift-dbaas-operator
  name: rosa-rds-inventory-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: rosa-rds-secret-store
    kind: SecretStore
  target:
    name: rosa-rds-inventory-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rosa-rds-inventory-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: openshift-dbaas-operator
  name: rosa-rds-shared-instance-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: rosa-rds-secret-store
    kind: SecretStore
  target:
    name: rosa-rds-shared-instance-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rosa-rds-shared-instance-credentials

